### PR TITLE
Fix entry file & load bootstrap CSS

### PR DESCRIPTION
**Pull request by liuzix**
### Changes
- Fixed webpack entry file so that React now renders normally.
- Changed docker-compose exposed port to 3000, which is the port `server.js` listens on.

### CODE REVIEW

**Review by bjia56 — APPROVED** [review]

**Comment by bjia56** [comment]
@liuzix did you include the changes to docker-compose?

**Comment by liuzix** [comment]
> @liuzix did you include the changes to docker-compose?

Now I have.

**Comment by bjia56** [comment]
ah ok I see it now

**Comment by bjia56** [comment]
testing github slack integration

**Comment by bjia56** [comment]
testing github slack integration

**Comment by bjia56** [comment]
testing github slack integration

**Pull request merged**
